#spring.application.name=shopapp
server:
port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 210303
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size:10MB
      max-request-size:10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  mail:
    host: smtp.gmail.com
    port: 587
    username: hobadat2003@gmail.com
    password: ryakwkufbaewciqg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    debug: true
api:
  prefix: api/v1
jwt:
  expiration: 5920000
  #30 days (s)
  secretKey: PstJjnP30Ohm2YKW/bgvGvk80UFeylLdzcbHcH136z4=

logging.level.org.springframework.security: DEBUG
logging.level.com.project.shopapp.filters.JwtTokenFilter: DEBUG
logging.level.org.springframework.mail: DEBUG



